Iter5
knstch/shortener pull request #20
Opened 2023-10-10 09:38 UTC by knstch

2023-10-10 10:42 UTC, edylcrm requested changes

2023-10-10 10:42 UTC, edylcrm commented on cmd/config/config.go
> +package config
Комментарии разделены на несколько типов:
**[BLOCKER]** - Проблема, не решив которую принять работу нельзя
**[LINT]** - Заменичение, опционально к выполнению.
**[FYI]** - просто ремарка

2023-10-10 10:42 UTC, edylcrm commented on internal/app/getMethod/getMethod.go
> +package getmethod
**[BLOCKER]** Давай какой-то по другому это назовем. В дальнейшем будет добавляться еще какое-то кол-во ручек и все их нужно как-то именовать

2023-10-10 10:42 UTC, edylcrm commented on cmd/shortener/main.go
> +	err := http.ListenAndServe(config.ReadyConfig.ServerAddr, RequestsRouter())
**[FYI]** Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-10 10:42 UTC, edylcrm commented on internal/app/getMethod/getMethod.go
> +	for k, v := range URLstorage.Data {
**[BLOCKER]** сложность такой реализации O(n) т.е. если у тебя будет 1 миллион записей в хранилище придется каждый раз перебирать этот миллион чтобы найти нужное значение. Можно сделать это на О(1):
```
value, ok := URLstorage.Data[url]
if !ok {
    return ""
}

return v
```

2023-10-10 10:42 UTC, edylcrm commented on internal/app/postMethod/postMethod.go
> +package postmethod
**[BLOCKER]** Здесь про название тоже самое что и getMethod

2023-10-10 10:42 UTC, edylcrm commented on internal/app/postMethod/postMethod.go
> +type Storage struct {
**[LINT]** я бы все таки вынес работу с хранилищем в отдельный пакет и завязал реализацию на interface

2023-10-10 10:42 UTC, edylcrm commented on internal/app/postMethod/postMethod.go
> +	counter++
[FYI] при большом кол-ве запросов здесь будет race condition. Защититься от нее можно при помощи sync.Mutex

2023-10-10 12:27 UTC, knstch commented on internal/app/postMethod/postMethod.go
> +package postmethod
Done

2023-10-10 12:27 UTC, knstch commented on internal/app/getMethod/getMethod.go
> +package getmethod
Done

2023-10-10 12:41 UTC, knstch commented on internal/app/postMethod/postMethod.go
> +type Storage struct {
Done

2023-10-10 12:50 UTC, knstch commented on internal/app/postMethod/postMethod.go
> +	counter++
Done

2023-10-11 09:44 UTC, edylcrm requested changes

2023-10-11 09:44 UTC, edylcrm commented on internal/app/getShortenLink/GetShortenLink.go
> +	URLstorage.Mu.Lock()
**[BLOCKER]** Давай все таки логику по поиску нужного значение перенесем в URLStorage.go
Дальше будут добавляться еще хранилища, чтобы весь код не переписывать. И здесь навязаться на интерфейс

2023-10-11 09:44 UTC, edylcrm commented on internal/app/postLongLink/postLongLink.go
> +	URLstorage.Mu.Lock()
**[BLOCKER]** Здесь тоже самое что и в getshortenlink.go

2023-10-11 15:55 UTC, edylcrm commented on internal/app/postLongLink/postLongLink.go
> +	URLstorage.Mu.Lock()
**[BLOCKER]** Вызов методов Lock() и Unlock() тоже надо перенести в URLstorage.go

2023-10-11 16:06 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +	Mu      *sync.Mutex
**[LINT]** Лучше все эти поля сделать приватными и создать отдельную функцию чтобы создавать Storage. Приватным их можно сделать назвав с маленькой буквы.
Нужно это для того, чтобы где-то из все этот mutex не был случайно вызван, что может привести к dead lock

2023-10-11 16:06 UTC, edylcrm approved these changes

2023-10-11 16:07 UTC, merged