Iter9
knstch/shortener pull request #36
Opened 2023-10-29 15:15 UTC by knstch

2023-10-30 05:35 UTC, edylcrm requested changes

2023-10-30 05:35 UTC, edylcrm commented on cmd/shortener/main.go
> +func init() {
[BLOCKER] такие функции лучше не использовать в своем коде. Иногда эти фукнции используются в библиотеках. Но при большом кол-ве такие функции могут вызывать не корректное поведение

2023-10-30 05:35 UTC, edylcrm commented on .github/workflows/shortenertest.yml
>          uses: actions/checkout@v2
**[BLOCKER]** -  Проблема, не решив которую принять работу нельзя
**[LINT]** - Заменичение, опционально к выполнению
**[FYI]** - просто ремарка

2023-10-30 05:35 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +	for _, links := range storage.Data {
[BLOCKER] Здесь сложность O(n) можно сделать за O(1) использую map

2023-10-30 05:35 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +	storage.Save(config.ReadyConfig.FileStorage)
[BLOCKER] запись в файл на каждое создание новой ссылки - очень дорогая операция. Лучше это делать в фоне batch запросами

2023-10-30 05:51 UTC, knstch commented on cmd/shortener/main.go
> +func init() {
Done

2023-10-30 06:04 UTC, knstch commented on internal/app/URLstorage/URLstorage.go
> +	for _, links := range storage.Data {
Done

2023-10-30 06:07 UTC, knstch commented on internal/app/URLstorage/URLstorage.go
> +	storage.Save(config.ReadyConfig.FileStorage)
Done

2023-11-01 08:28 UTC, edylcrm approved these changes

2023-11-01 08:28 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +	storage.Save(config.ReadyConfig.FileStorage)
[LINT] Метод Save возвращает ошибку и лучше ее здесь обработать

2023-11-01 08:28 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +	if len(storage.Data)%30 == 0 || len(storage.Data) < 2 {
[LINT] необычное решение. Здесь можно было использовать горутину и какой-то time.Ticker. Мы же все таки на го пишем :)

2023-11-01 08:29 UTC, merged