Iter13
knstch/shortener pull request #40
Opened 2023-11-12 09:27 UTC by knstch

2023-11-14 05:51 UTC, edylcrm requested changes

2023-11-14 05:51 UTC, edylcrm commented on internal/app/URLstorage/URLstorage.go
> +		db, err := sql.Open("pgx", config.ReadyConfig.DSN)
[BLOCKER] давай здесь отделим логику для хранения данных в БД и сделаем для этого отдельную структуру. И на основании конфига будет создаваться нужный вид хранилища. А там где нужно использовать хранилище будет использоваться interface

2023-11-14 05:51 UTC, edylcrm commented on cmd/shortener/main.go
> +	if shortenURL, err := getShortenLink.GetShortenLink(url, URLstorage.StorageURLs); shortenURL != "" {
[BLOCKER] А если придет пустая строка и ошибка? Ее не нужно логировать?
Я бы написал как то так:
```
func getURL(res http.ResponseWriter, req *http.Request) {
	url := chi.URLParam(req, "url")

	shortenURL, err := getShortenLink.GetShortenLink(url, URLstorage.StorageURLs)
	if err != nil {
		logger.ErrorLogger("Can't find link: ", err)
		http.Error(res, "Bad Request", http.StatusBadRequest)
		return
	}

	if shortenURL == "" {
		http.Error(res, "Bad Request", http.StatusBadRequest)
		return
	}

	res.Header().Set("Content-Type", "text/plain")
	res.Header().Set("Location", shortenURL)
	res.WriteHeader(307)
	res.Write([]byte(shortenURL))
}
```

2023-11-14 05:51 UTC, edylcrm commented on cmd/shortener/main.go
> +func pingDB(res http.ResponseWriter, req *http.Request) {
[LINT] тут можно применить ранний return и сделать код чуть читабельней без if/else
```
func pingDB(res http.ResponseWriter, req *http.Request) {
	err := DBConnect.OpenConnection(config.ReadyConfig.DSN)
	if err != nil {
		http.Error(res, "Can't connect to DB", http.StatusInternalServerError)
		return
	}
	
	res.Header().Set("Content-Type", "text/plain")
	res.WriteHeader(http.StatusOK)
	res.Write([]byte("Connection is set"))
}
```

2023-11-14 05:51 UTC, edylcrm commented on internal/app/DB/checkDuplicate/checkDuplicate.go
> +func FindShortLink(longLink string, db *sql.DB) string {
[BLOCKER] Давай поменяем сигнатуру метода на `FindShortLink(ctx context.Context, longLink string, db *sql.DB)` чтобы здесь не создавался новый context. Для каждого нового запроса создается свой отдельный контенкст который можно получить из request. Если по какой-то причине пользователь закроет страницу, то context будет отменем и уже не нужно делать запрос в БД и если здесь передать context который создался при запросе то драйвер БД сам отменит запрос

2023-11-14 05:51 UTC, edylcrm commented on internal/app/DB/findData/findData.go
> +func FindData(dsn string, shortLink string, db *sql.DB) (string, error) {
[BLOCKER] здесь тоже давай сделаем `FindData(ctx context.Context, shortLink string, db *sql.DB)`

2023-11-14 05:51 UTC, edylcrm commented on internal/app/DB/insertData/insertData.go
> +func InsertData(longLink string, db *sql.DB) (string, int, error) {
[BLOCKER] func InsertData(ctx context.Context, longLink string, db *sql.DB) (string, int, error). Так же я бы тут предложил убрать второй параметр int (statusCode) и унести его на уровень handlers. Определять на основании ошибки какой код ответа нужен. Здесь этого быть не должно, здесь логика записи в БД, знание какой http код отдать не ответственность этой штуки

2023-11-17 09:20 UTC, edylcrm approved these changes

2023-11-17 09:20 UTC, edylcrm commented on internal/app/storage/psql/psqlStorage.go
> +func (storage *PsqURLlStorage) findShortLink(longLink string) string {
[LINT] Здесь тоже context надо прокидывать

2023-11-17 09:20 UTC, edylcrm commented on internal/app/storage/psql/psqlStorage.go
> +func (storage *PsqURLlStorage) FindLink(url string) (string, error) {
[LINT] И здесь context

2023-11-19 10:26 UTC, knstch commented
Completed

2023-11-19 10:26 UTC, merged